### PR TITLE
Reorg for githubpages

### PR DESCRIPTION
**Pull request by hansieodendaal**
Hi there,

This is a proposal for a re-organized repo for Github Pages. Links created to topics with presentations only. High level introductory definitions added for each category of information.

Your review comments will be much appreciated.

Thanks

### CODE REVIEW

**Comment by CjS77** [comment]
@hansieodendaal I've pushed an alternative method of viewing presentations (See the RGB Protocol presentation) that I think is a bit more user-friendly

**Comment by hansieodendaal** [comment]
Wow, that looks great! Will change all

**Comment by CjS77** [comment]
👍

**Comment by CjS77** [comment]
`mdbook test` was failing on text that looks like this:

<pre>
```
  FantamCoin Release notes 2.0.0
  - Fantomcoin 2.0 by XDN-project, major FCN update to the latest
...
```
</pre>

To fix this, you need to tell mdbook that this isn't rust code:
<pre>
```text
  FantamCoin Release notes 2.0.0
  - Fantomcoin 2.0 by XDN-project, major FCN update to the latest
...
```
</pre>

**Pull request merged**
