### PR TITLE
Probabilistic Attack Vector Analysis Building Blocks - formatting

### PR DESCRIPTION
**Pull request by anselld**
Hi @Kevoulee, I've completed the first part of the technical editing process, i.e. formatting. Please could you review my formatting changes and let me know if you are happy, or if you'd like any changes. I'll then do the language editing.
Two questions, please:
1. Under 'Law of large numbers', the second paragraph is incomplete. How should the sentence end?
2. Reference [[9]] in the text is not 'live'. I've fixed other references, but cannot establish the problem with this one. Can you please help?
Please let me know when I can proceed with the language editing. Thanks.

### CODE REVIEW

**Comment by Kevoulee** [comment]
Thank you @anselld for formatting changes. I have completed the sentence for 'Law of Large Numbers'- so sorry, and the reference link for [9] is fixed. Please proceed with language editing. Many thanks

**Comment by anselld** [comment]
Hi @Kevoulee, thanks so much for your help on my questions on the formatting. I've completed the technical editing. Please review my edits and let me know if you're happy. I have the following questions, please:

1. Reference is made to the 2002 Kademlia Paper (two occurrences in the text). Should a reference be included under the list of references, and a reference number given in the text?
2. There is reference to a 'hotlink' in the text. Is it still to be included?

Thanks and regards
Denise

**Comment by Kevoulee** [comment]
Hi @anselld, thank you so much for the review- all is great. 

For your questions, first, I should have added a reference for the Kademlia paper: 

[16] P. Maymounkov and D. Mazières, "Kademlia: A Peer-to-peer  Information System Based on the XOR Metric" [online]. Available: https://pdos.csail.mit.edu/~petar/papers/maymounkov-kademlia-lncs.pdf. Date accessed: 2019‑07‑18.

"Kademlia"

Second, the hotlink phrase should be removed- it was a reminder, that I decided against. 

Please let me know if I can make these changes or if you will. 

Thank you again and so sorry for the inconvenience.

**Comment by anselld** [comment]
Hi Kev

 

I’ll make the changes.

 

Regards

Denise

**Comment by anselld** [comment]
Hi @Kevoulee , I have deleted the reference to the hotlink and included [[16]], as well as the two inline text references. Please let me know if you'd like any other changes.

Regards, Denise

**Pull request merged**
