### PR TITLE
Tor (Section 6.11) ready for review

### PR DESCRIPTION
**Pull request by anselld**
Hi @leet4tari, I've formatted your report in accordance with the TLU Style Guide. I've also edited the text (language, spelling, etc). Please let me have your comments.

Some questions, please:
1. Reference [3] is not available. Please help with a new link.
2. In the report, no reference is made to [7] and [8], which were among your original references. Where should they fit in?
Thanks and regards
Denise

### CODE REVIEW

**Comment by leet4tari** [comment]
Reference [3] will not be accessible unless you running the Tor Browser and I think you should be able to see the link ending in ```.onion```, as this is part of the secure/hidden services?  
  
Reference [7] and [8] is where some of the info I initial read and found useful, think it should be some how list, but I am not sure what is a nice way?

**Comment by anselld** [comment]
Hi @leet4tari, thanks for the feedback regarding the references. I could move [7] and [8] to under Appendix B, links of interest, as background info. I'll make the change. Anything else from your side?

**Comment by leet4tari** [comment]
That all works for me. Only other thing I was thinking about, is my bad pun title, ```Tor || !2 Tor```, is a programming pun ... ```||``` means ```or```, ```!``` means ```not```, which ties into the conclusion ... but the humor might be lost on none programmers.

**Comment by anselld** [comment]
Hi @leet4tari , I've included [7] and [8] in Appendix B. Your pun was totally lost on me - sorry! But I like it, now that I understand it.  I'd like to include it under a new heading and explain it to others like me - please see new heading 'Purpose of this Report' in my latest commit. Please let me know what you think. Feel free to change it, please.

**Comment by leet4tari** [comment]
Thank you very much! Last two notes, not too be difficult, but I think your feedback has sparked something in me. First, I am not a programmer nor call myself a programmer, but I do program if I have too. I would not want to offend any real programmers.  ;-)  
  
Second, the third URL, referring to ```DuckDuckGo Search engine [[3]]```, might be worth noting, that the link will not work unless using the Tor Browser. Not sure what would be a good way to note that, as it seems that you might not be the only person who does not notice this and might think the link is broken too. I would just add a note in brackets, but that might be frown on. I am open too your suggestions here.

**Comment by anselld** [comment]
Hi @leet4tari , thanks for your feedback. I'll update the report and send another commit. It's great to keep the readers of your reports informed.

**Comment by anselld** [comment]
Hi @leet4tari , please have a look at my minor changes to the report and let me know what you think. Regarding the 'broken link' issue, I added a note, as you suggested, under 'References', alongside [3] and [4]. I also included the note info in the 'pop-up' text of [3] and [4] in the body of the report, for clarity.

**Comment by leet4tari** [comment]
Thank you for the assist. Last few things to make perfect.  
  
Ref [4], will work if you using Tor or not, it is a URL to report if you using Tor. Basically a self-check or show how easy it is, for a site to know that you using Tor or not. I think it best to remove the incorrect note on Ref [4], that it will not work outside of the Tor browser or network.  
  
```Installation Instructions```, I had left the direct link to the download page - https://www.torproject.org/download/ ... I wanted to show how quick and easy it is to get the Tor Browser package. It is just an extra click form the homepage, but I think the direct download page is better?  
  
```Its browser is the only browser that provides secure accessibility to .onion sites.``` - This statement is not quite right. I think I was trying to say that the Tor Browser is an easy way to access ```.onion``` sites easy and securely. You do need the Tor network to access ```.onion``` sites, but you can also setup any browser to use the Tor services.  
  
Last thing, which is more of a big ask, after re-reading the report as a whole, I think it might be an idea to note that this report was focused on the ``` Tor Browser``` and not the ```Tor service/network``` ... I feel like I might just need to update something to note that and possible add ```TorBrowser``` to a few of the references of Tor.

**Comment by anselld** [comment]
Hi @leet4tari , please make any changes you'd like - let me know when you're done, and I'll give the report a final once-over.

**Comment by hansieodendaal** [comment]
Hi @leet4tari, I propose you squash and merge this editing branch into your own branch if you are happy with the formatting and editing (or I can do it on your behalf). Then when you have updated the report as you propose @anselld can have another look at it.

**Pull request merged**
