### PR TITLE
Grin-BEAM comparison, draft report for review

### PR DESCRIPTION
**Pull request by philipr-za**
Here is my first draft of the report. It will almost certainly need another proof read.

It was difficult to decide on what dimensions to perform this comparison. In the end they are both implementing Mimblewimble but they had a couple unique features that I discussed, they used different PoW algorithms but the biggest differences were in their Governance models and monetary policies.

I might have gone into too much depth on the Cuckoo cycle PoW but lets see what you think about the current layout. Let me know where you think I went into too much depth and where I summarized too much.

### CODE REVIEW

**Comment by philipr-za** [comment]
The review should happen as a Git Issue.

**Comment by philipr-za** [comment]
As requested I reopened this PR to be the forum for review and discussion.

**Comment by hansieodendaal** [comment]
Hi @philipr-za  , good job! If you can incorporate these comments, I think the general quality of your report would be enhanced. 

- [ ] References: Use internal links for references and enable opening of URLs at the same time. This dead reference ([1]) in the text will become this 'live' reference ([1]) that is clickable and with data tool tip shown. See example below.

       Referenced in the text like this:
       [[1]][\[1\]]

       Include reference like this:
       [[1]][\[1\]]<space>Title,<space>Author (if paper),<space>URL,<space>Date accessed.

       [\[1\]]:<space>URL<space>
       "Title line 1
       Title line n"

- [ ] Nice touch with the figure captions! I am beginning to feel at home :-). Please make all figure captions bold text to let them stand out a bit.

- [ ] Table of Contents: Insert a 'Contents' sections after 'Introduction' with a table of contents, reflecting the outline and internal links to the different headings. Example:

      ## Contents
      - [Grin vs. BEAM, a Comparison](#Grin-vs.-BEAM,-a-Comparison)
         - [Introduction](#Introduction)
         - [Contents](#Contents)
         - [Unique features of Grin vs BEAM](#Unique-features-of-Grin-vs-BEAM)
         etc.

- [ ] In "_The Mimblewimble protocol describes how transacting parties will interactively work to build a valid transaction while keeping their private keys, used to prove ownership of transaction outputs, secret and keeping the value of their transaction known only to them._ " private keys are secret per definition so not wow to keep it secret... The actual point here is '_not to be required to reveal a public key_'. Rewrite to bring this fact across.

- [ ] "_The protocol also performs a process called cut-through which **aggregates** transactions by eliminating intermediary transactions._" This actually condense transactions, not aggregate them.

- [ ] This make it sound as if there are scripts in Mimblewimble: "_... to build adaptor signatures that allow for encoding of many of the functions that scripts are used for in a Mimblewimble chain._". 
rephrase to something like: "_... to build adaptor signatures that allow for encoding of many functions in a Mimblewimble block chain that scripts would usually be used for._".

- [ ] Capitalization & general:  
 "_Both project are ..._" to "_Both **projects** are ..._"
"_... mostly in russian ..._" to "_... mostly in **Russian** ..._", 
"_... for english readers ..._" to "_... for **English** readers ..._",
"_... to only a single ~~**single**~~ randomly ..._"
"_... random number of hope along ..._" to "_... random number of **hops** along ..._"
"_... BEAM has designed a wallet ~~**designed**~~ for ..._"
"_... intensive and thus mke obsolete ..._" to "_... intensive and thus **make** obsolete ..._"

- [ ] "**Unique features of Grin vs BEAM**": Include, elaborate and compare BEAM vs. Grin 
"Confidential and public UTXOs",
 "Explicit UTXO incubation period",
 "One side transfers", 
"Timelocked transactions, lower and upper blockchain height thresholds.", 
"Embedded contract: BEAM kernels may optionally contain a signed contract...", 
"Eliminating transaction kernels" vs. "obtain the Merkle proof for this kernel ... be able to prove it was there.",
"system definition Hash inside the block header, system definition hash vs. block header
hash"
"BEAM nodes use a Radix‑Hash tree"
"in BEAM there is no need to include the Merkle proofs in the compressed history"
"Less motivation to produce empty blocks"
"Simpler protocol for SPV clients"

- [ ] "Grin has adapted this approach to work with Mimblewimble transactions". BEAM did as well as far as I can see (https://www.scribd.com/presentation/385995861/Beam-Technology-Presentation).

- [ ] "**Proof of work (PoW) mining algorithm**": 
Provide only general comparison of the 2x PoW algorithms, too much discussion about the different algorithms. Merged mining on the table or not? The long discussions are however interesting and could maybe go to an Appendix.
Seeing that both block chains potentially suffer the ASIC problem before launch, speculate about the possibility to implement both PoW mining algorithms and possibly a 3rd like CryptoNigt v7 including one to be merged mined, similar to what Myriad did (https://github.com/tari-labs/tari-university/blob/master/merged-mining/merged-mining-scene/MergedMiningIntroduction.md#myriad-510-with-bitcoin-1-or-litecoin-6). Referencing TLU report here should be enough.

- [ ] "_The main differences between the projects are the chosen PoW algorithms, monetary policy and their Governance models._" The difference seems to be much more than this...

- [ ] Add summary table of differences and similarities in "**Conclusions, Observations, Recommendations**"

- [ ] References: 
Add? "https://www.scribd.com/document/385080303/BEAM-Description-Comparison-With-Classical-MW"
Add? "https://www.scribd.com/document/387888141/Presentation-of-Mimblewimble-at-the-Zero-Knowledge-Proof-Summit-Berlin-September-2018"
Add? "https://www.scribd.com/presentation/385995861/Beam-Technology-Presentation"
Add? "https://www.scribd.com/document/382680718/Beam-Position-Paper-V-0-1"

**Comment by philipr-za** [comment]
Thanks for all the comments. I have made the changes as requested. I had missed the one BEAM document that outlines their unique features for my first draft so I have added quite a bit more material to this draft. It could probably do with someone else giving it a proof read for language but content-wise I think it is done.

**Comment by hansieodendaal** [comment]
Nice @philipr-za !

**Pull request merged**
