### PR TITLE
Step 2 in consistency edit - minor edits.

### PR DESCRIPTION
**Pull request by anselld**
Hi @hansieodendaal , please could you review my minor edits to Sections 2.2, 3.1, 3.2, 4.1, 5.1, 6.2, 6.4 and 6.5.
In Cayle's chapter, Section 6.2, there is some inconsistency in the table headings: some are centered and some are left justified. I am not sure how to fix this.
Please let me have your comments, when you get a chance.

Thanks and regards
Denise

### CODE REVIEW

**Comment by hansieodendaal** [comment]
Thanks @anselld, you can continue.
- Cannot fix table headings in 6.2, so we can leave as is.
- Please be mindful not to introduce too much white space where it has no effect in mdBook or will not improve the readability of the raw text files.
- We should not add &nbsp; before numbers that is not part of a single concept. The overhead of managing this across all reports is to big.

When you get to edit the TOCs, please note that
- Report 1.4 has an alignment problem in the TOC
- Report 5.1 needs bullets in the TOC

Regards

**Comment by anselld** [comment]
Hi @hansieodendaal , thanks very much for the call and your comments. Appreciated.

**Comment by anselld** [comment]
Hi @hansieodendaal , if you get a chance, please look at my commit containing edits to Section 3.2 and the small changes I made to Section 3.1 for consistency. Thanks.

**Comment by hansieodendaal** [comment]
Perfect @anselld, please continue.

**Comment by anselld** [comment]
Hi @hansieodendaal. When you get a chance, please have a look at my latest commit and let me have your comments. This is 'Step 3' in the process, i.e. references, spacing in lists, etc., for Sections 2.2 to 6.10.  There are a few other minor changes, but all should be easily visible. I used the 'diff' function that you showed me this morning. It is really useful. Thanks!

**Comment by hansieodendaal** [comment]
Hi @anselld, looking really good and consistent overall, thanks. Some notes:

**Pull request merged**
