### PR TITLE
Ks network analysis report 1 edits

### PR DESCRIPTION
**Pull request by anselld**
Hi @Kevoulee 

Please see my suggested edits shortly. I will send you some questions or comments on each of the three reports. Please see these before you merge.

Enjoy your day.
Regards
Denise

### CODE REVIEW

**Comment by Kevoulee** [comment]
Thank you @anselld

**Comment by anselld** [comment]
Hi @Kevoulee 

The only comments I have are on Section 8.2. The other two reports look good.

In Section 8.2:

- Please update index on left to reflect new title.

- Under 'Implementation', the Tari labs modelling repository link does not work.

- From under 'Variation of Total Number of Nodes with Committee Size 10' until the conclusion, the links do not work. There is an error message re the site.

- In many of the graphs, from 'Variation of Total Number of Nodes with Committee Size 10' onwards, the decimal comma is used instead of the decimal point. This is inconsistent with the text. Is it possible to correct this?

Regards
Denise

**Comment by anselld** [comment]
Hi Kev
For consistency, I edit it terms of the Tari Style Guide (Section 10 of the TLU content). Editing convention is numbers from one to nine that appear in text are written out, and numbers from 10 upwards appear as numerals.

**Comment by hansieodendaal** [comment]
> Hi Kev
> For consistency, I edit it terms of the Tari Style Guide (Section 10 of the TLU content). Editing convention is numbers from one to nine that appear in text are written out, and numbers from 10 upwards appear as numerals.

Hi @anselld, maybe time to have a look at the TLU Style Guide again?

**Comment by anselld** [comment]
Hi @Kevoulee , I have checked your links again - only one is inaccessible. It is the first link under 'Variation of Total Number of Nodes with Committee Size 10'. The rest are good.

Hi @hansieodendaal , thanks for the suggestion regarding reviewing the Style Guide - will do.

**Comment by Kevoulee** [comment]
@anselld Thank you

**Pull request merged**
