### PR TITLE
Da introduction to applications of byzantine consensus mechanisms

### PR DESCRIPTION
**Pull request by anselld**
Hi Kev, I've combined all the sections into one report. Please could you look at the contents list under the title, and let me know if I've got the formatting right. I'll do the editing and complete the references once you're happy with the structure of the report. Thanks.

### CODE REVIEW

**Comment by anselld** [comment]
@Kevoulee , regarding PR146, I noticed that there was only, one appendix, i.e. A. However, not all the info belongs in Appendix A, so I created a new Appendix B. Please have a look and let me know if this is correct.

**Comment by Kevoulee** [comment]
@anselld this all looks correct. Thank you so much.

**Comment by anselld** [comment]
Hi @Kevoulee, thanks. I'll continue with the rest of the formatting and the editing.

**Comment by anselld** [comment]
Hi @Kevoulee  and @hansieodendaal 
I've completed the editing, as well as the formatting of the appendices.
Please let me know if you'd like any changes.

**Comment by anselld** [comment]
Hi @Kevoulee and @hansieodendaal 
Looking at the rendered version, I see that the structure is incorrect from 'References' down to 'Contributors'. I will fix the indents and structure and commit and push the file again.

**Comment by anselld** [comment]
Hi @Kevoulee and @hansieodendaal 
I have corrected the structure of the contents and have committed and pushed the updated report.
Regards, Denise

**Comment by anselld** [comment]
Hi @Kevoulee and @hansieodendaal 
I still need to add the list of contributors. Will do so after your review.

**Comment by anselld** [comment]
Hi @Kevoulee and @hansieodendaal, I've inserted the contributors and checked all the links and references. Please let me know if you'd like any changes.

**Comment by Kevoulee** [comment]
@anselld thank you. This is great.

**Pull request merged**
