### PR TITLE
R1cs bulletproofs final edits da

### PR DESCRIPTION
**Pull request by anselld**
Hi @hansieodendaal and @Empiech007
This looks good. I only have one question, please. In Table 3, No. 6, it is unclear what creates its own transcript.
All the links work, as well as the contents.
Please let me have your comments.
Thanks and regards.

### CODE REVIEW

**Comment by anselld** [comment]
Hi @hansieodendaal and @Empiech007 

Another question and observation:

1. In the last sentence under Conclusions, Observations and Recommendations, '... provides greater opportunities'. Greater opportunities for what?

2. The conclusion should reflect whether the aim of the report, set out in the list in the introduction, has been achieved. 

Regards
Denise

**Comment by hansieodendaal** [comment]
> This looks good. I only have one question, please. In Table 3, No. 6, it is unclear what creates its own transcript.

Changed to: `The verifier creates its own transcript. `

**Comment by hansieodendaal** [comment]
> 1. In the last sentence under Conclusions, Observations and Recommendations, '... provides greater opportunities'. Greater opportunities for what?

Sentence rewritten as `This framework provides great opportunities in building blockchain-enabled confidential digital asset schemes.`

> 2. The conclusion should reflect whether the aim of the report, set out in the list in the introduction, has been achieved.

This sentence added: `The use of ZK proofs for arithmetic circuits and programmable constraint systems has evolved considerably as illustrated in Table 2.` The rest have been covered sufficiently.

**Comment by hansieodendaal** [comment]
Thank you @anselld, all questions resolved.

**Pull request merged**
