### PR TITLE
Readme mdbook link

### PR DESCRIPTION
**Pull request by Kevoulee**
@CjS77 I have made some changes to the README on the GitHub page and added a section called introduction to the SUMMARY with links as you suggested on mdbook.

### CODE REVIEW

**Comment by CjS77** [comment]
Cool. I think the Guiding Principles and Submission steps can stay in the README. Everything else looks good for now. We should think about the best way to present the learning paths going forward, once there's more content.

**Comment by hansieodendaal** [comment]
Hi @Kevoulee , my review changes below.

**With README.md**

- [ ] Rather use commas as a pause in a sentence than dashes: "_a refresher-- but we think_" to "_a refresher, but we think_"

- [ ] Suggest make the online book link stand out a bit by making it bold, example: "_The Tari Labs University online book is rendered **[here](https://tari-labs.github.io/tari-university/)**._"

- [ ] The last three presentations are pushed out and we need to add your two and my two presentations. Mine will be called "_Bulletproofs and Mimblewimble (part 1)_" and "_Bulletproofs and Mimblewimble (part 2)_". 

- [ ] To minimize maintenance in README.md we ideally need the schedule of upcoming talks to be a live embedded link/frame from somewhere else where we can maintain it, but this is not supported in GitHub as far as I know. We also need to be more inclusive of the Tari community. So my suggestion is not to publish the dates but rather change the date column to "_Presentation Link_" and then to embed the Zoom meetings' links there, which will be seen like this when opened:
    zoom-1
    Instead of "_TLU's Zoom Meeting_" as a topic we could write the actual topic, example "_Presentation: Fraud Proofs (Duration: 1.5 hours)_"
    The table can then be updated less frequently, let's say once a month.

- [ ] So, in line with the comment above, we can add an introductory note above the table, like "_To join the live presentation open the respective meeting link below._"

- [ ] We also need to publish links to the respective reports that will be presented as well as to the GitPitch presentations. The problem here is everything will not necessarily be available in master at the time. My suggestion is thus to add another paragraph below the table redirecting the reader to a Google Presentation with detail information that can be maintained easily. This message could be: "_Detail schedule available **[here](https://docs.google.com/presentation/d/14bRWRcGXLG59t5BxUpFJkjHYF7ij8euoy718syXNK1w/present?includes_info_params=1#slide=id.p)**_". (**Note:** See example embedded [Google Presentation](https://docs.google.com/presentation/d/14bRWRcGXLG59t5BxUpFJkjHYF7ij8euoy718syXNK1w/present?includes_info_params=1#slide=id.p) with links to mdbook report, GitPich presentation and Zoom meeting.)

- [ ] We could also opt not to publish the table in README.md at all but just to have the link to the Google Presentation. That would be by preference. In this case the only sentence under "**_Upcoming Talks_**" could be "_To join the live presentation meeting, view the detail report or to get a link to the presentation detail open the schedule available **[here](https://docs.google.com/presentation/d/14bRWRcGXLG59t5BxUpFJkjHYF7ij8euoy718syXNK1w/present?includes_info_params=1#slide=id.p)**._"

**With introduction.md**

- [ ] With Learning Paths, use consistent single space before and after each dash to separate the topic from the description.

- [ ] With Presentations, change the heading to "_**Other Presentations**_" or similar so the reader does not expect this to be an exhaustive list of presentations.

- [ ] With Reports, the embedded links should point to the relative paths of the mdbook chapter/section not to the online version; this way we will be able to debug the links locally on a branch. Example use "_(../layer2scaling/more-landscape/landscape-update.md)_" instead of "_(https://tari-labs.github.io/tari-university/layer2scaling/layer2scaling-landscape/landscape-update.html)_"

- [ ] With Reports, replicate the TOC to give context to the topics

Thanks,
Hansie.

**Comment by CjS77** [comment]
fixes #86

**Comment by Kevoulee** [comment]
@CjS77 @hansieodendaal  I have made the changes, hope it's alright.

**Comment by hansieodendaal** [comment]
fix #86

**Comment by hansieodendaal** [comment]
Fixes #86

**Pull request merged**
